<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="comigsformswidgets"
    nsURI="http://example.com/comigsformswidgets" nsPrefix="comigsformswidgets">
  <eClassifiers xsi:type="ecore:EClass" name="NavigationWidgetPropertySet" eSuperTypes="http://www.tibco.com/forms/model/form#//CustomControlPropertySet"/>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentListWidgetPropertySet" eSuperTypes="http://www.tibco.com/forms/model/form#//CustomControlPropertySet"/>
</ecore:EPackage>
